blank_issues_enabled: true
contact_links:
  - name: Security policy
    url: https://github.com/schibsted/WAAS/blob/main/SECURITY.md
    about: For creating a security report.
  - name: Code of Conduct
    url: https://github.com/schibsted/WAAS/blob/main/CODE_OF_CONDUCT.md
    about: Information on how to behave in the community.
